import { Inter } from "next/font/google";
import "./globals.css";
import BoardGuruContext from "@/context/BoardGuruContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Board Guru",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BoardGuruContext>{children}</BoardGuruContext>
      </body>
    </html>
  );
}
